apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:

  name: nginx-app-stg
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/abdoriax/nginx-argocd-app.git
    targetRevision: HEAD
    path: 'k8s/overlays/staging'

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-app-stg

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
