apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-dev
  namespace: nginx-app-dev
  labels:
    app: nginx-app-dev
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx-app-dev
  template:
    metadata:
      labels:
        app: nginx-app-dev
    spec:
      containers:
        - name: nginx-container
          image: ghcr.io/abdoriax/nginx-argocd-app:v0.11.0-alpha
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "100m"
