apiVersion: v1
kind: Service
metadata:
  name: nginx-app-dev-service
  namespace: nginx-app-dev
spec:
  selector:
    app: nginx-app-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
