apiVersion: v1
kind: Service
metadata:
  name: nginx-app-prod-service
  namespace: nginx-app-prod
spec:
  selector:
    app: nginx-app-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
