name: Reusable Comment Parser

on:
  workflow_call:
    inputs:
      comment_body:
        description: 'The full body of the issue comment'
        required: true
        type: string
      head_sha:
        description: 'The SHA of the HEAD of the default branch'
        required: true
        type: string

jobs:
  parse-and-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Comment Data
        id: parsed_comment
        run: |
          # Read the comment body into a variable
          COMMENT="${{ inputs.comment_body }}"
          
          # Use awk to easily grab the second and third "words"
          # Word 1: /service
          # Word 2: operation (plan/apply)
          # Word 3: environment (development/staging/production)
          OPERATION=$(echo "$COMMENT" | awk '{print $2}')
          ENVIRONMENT=$(echo "$COMMENT" | awk '{print $3}')
          
          # Check if the extracted values are valid
          if [[ "$OPERATION" != "plan" && "$OPERATION" != "apply" ]]; then
            echo "Error: Invalid operation. Must be 'plan' or 'apply'."
            exit 1
          fi
          
          if [[ "$ENVIRONMENT" != "development" && "$ENVIRONMENT" != "staging" && "$ENVIRONMENT" != "production" ]]; then
            echo "Error: Invalid environment. Must be 'development', 'staging', or 'production'."
            exit 1
          fi
          
          echo "operation=$OPERATION" >> $GITHUB_OUTPUT
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

      - name: Echo Comment Information
        run: |
          echo "--- Comment Trigger Information ---"
          echo "Commit SHA:   ${{ inputs.head_sha }}"
          echo "Operation:    ${{ steps.parsed_comment.outputs.operation }}"
          echo "Environment:  ${{ steps.parsed_comment.outputs.environment }}"
          echo "-----------------------------------"
