name: Reusable Comment Parser

on:
  workflow_call:
    inputs:
      github_event:
        description: 'The JSON payload from the original trigger event'
        required: true
        type: string

jobs:
  parse-and-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Comment Data
        id: parsed_comment
        run: |
          COMMENT=$(echo '${{ inputs.github_event }}' | jq -r .comment.body)
          OPERATION=$(echo "$COMMENT" | awk '{print $2}')
          ENVIRONMENT=$(echo "$COMMENT" | awk '{print $3}')
          # Note: The SHA is not available in the issue_comment payload by default.
          # If needed, it must be fetched via API in the orchestrator.
          SHA="N/A (Requires API call in orchestrator)"

          echo "operation=$OPERATION" >> $GITHUB_OUTPUT
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Echo Comment Information
        run: |
          echo "--- Comment Trigger Information ---"
          echo "Commit SHA:   ${{ steps.parsed_comment.outputs.sha }}"
          echo "Operation:    ${{ steps.parsed_comment.outputs.operation }}"
          echo "Environment:  ${{ steps.parsed_comment.outputs.environment }}"
          echo "-----------------------------------"
