name: Trigger on Service Comment

on:
  issue_comment:
    types: [created]
    startsWith: '/service'

permissions:
  contents: write

jobs:
  call_orchestrator:
    name: Call Orchestrator for Comment
    uses: ./.github/workflows/orchestrator.yaml
    with:
      github_event: ${{ toJson(github.event) }}
