# name: Main Deploy Workflow

# on:
#   push:
#     tags:
#       - 'v*.*.*'

# permissions:
#   contents: write
#   packages: write

# jobs:
#   call_ci_workflow:
#     name: Call Reusable CI Workflow
#     uses: abdoriax/reusable-workflows/.github/workflows/ci.yaml@main
#     with:
#       github_event: ${{ toJson(github.event) }}
#     secrets: inherit

name: Main Deploy Workflow

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  call_parser_workflow:
    name: Call Reusable Parser Workflow
    uses: ./.github/workflows/reusable-parser.yml
    with:
      github_event: ${{ toJson(github.event) }}