name: Orchestrator Workflow

on:
  workflow_call:
    inputs:
      github_event:
        description: 'The JSON payload from the original trigger event'
        required: true
        type: string
      event_name:
        description: 'The event name that triggered the caller workflow'
        required: false
        type: string

jobs:

  echo_event_type:
    name: Output GitHub Event Name
    runs-on: ubuntu-latest
    steps:
      - name: Echo the original event name
        run: |
          echo "The trigger event is: ${{ inputs.event_name }}"

  call_tag_parser:
    name: Call Tag Parser
    if: ${{ inputs.event_name == 'push' }}
    uses: ./.github/workflows/tag-parser.yaml
    with:
      github_event: ${{ inputs.github_event }}

  call_comment_parser:
    name: Call Comment Parser
    if: ${{ inputs.event_name == 'issue_comment' }}
    uses: ./.github/workflows/comment-parser.yaml
    with:
      github_event: ${{ inputs.github_event }}