name: Main Orchestrator Workflow

on:
  workflow_call:
    inputs:
      trigger_type:
        description: "The type of event that triggered the orchestrator ('tag' or 'comment')"
        required: true
        type: string
      github_event:
        description: 'The JSON payload from the original trigger event'
        required: true
        type: string

permissions:
  contents: read

jobs:
  call_tag_parser:
    name: Call Tag Parser
    if: startsWith(fromJson(inputs.github_event).ref, 'refs/tags/')
    uses: ./.github/workflows/tag-parser.yaml
    with:
      github_event: ${{ inputs.github_event }}

  call_comment_parser:
    name: Call Comment Parser
    uses: ./.github/workflows/comment-parser.yaml
    with:
      comment_body: ${{ fromJson(inputs.github_event).comment.body }}
      head_sha: ${{ fromJson(inputs.github_event).issue.pull_request.head.sha }}
