name: Main Orchestrator Workflow

on:
  workflow_call:
    inputs:
      github_event:
        description: 'The JSON payload from the original trigger event'
        required: true
        type: string

permissions:
  contents: read

jobs:
  call_tag_parser:
    name: Call Tag Parser
    if: fromJson(inputs.github_event).ref != null && startsWith(fromJson(inputs.github_event).ref, 'refs/tags/')
    uses: ./.github/workflows/tag-parser.yaml
    with:
      event_json: ${{ inputs.github_event }}

  call_comment_parser:
    name: Call Comment Parser
    if: fromJson(inputs.github_event).action == 'created' && fromJson(inputs.github_event).issue != null && fromJson(inputs.github_event).comment != null
    uses: ./.github/workflows/comment-parser.yaml
    with:
      event_json: ${{ inputs.github_event }}
