name: Tag Parser

on:
  workflow_call:
    inputs:
      github_event:
        description: 'The JSON payload of the github.event from the caller workflow'
        required: true
        type: string

jobs:
  tag-parse-and-echo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Parse Event Data
        id: parsed_data
        run: |
          sha=$(echo '${{ inputs.github_event }}' | jq -r .after)
          tag_name=$(echo '${{ inputs.github_event }}' | jq -r .ref | sed 's!refs/tags/!!')
          
          echo "sha=$sha" >> $GITHUB_OUTPUT
          echo "tag=$tag_name" >> $GITHUB_OUTPUT

      - name: Find Branch Name from Commit SHA using GitHub API
        id: branch_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          COMMIT_SHA: ${{ steps.parsed_data.outputs.sha }}
        run: |
          echo "Finding branches for commit SHA: $COMMIT_SHA"

          BRANCHES_RESPONSE=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$REPO/commits/$COMMIT_SHA/branches-where-head")

          BRANCH_NAME=$(echo "$BRANCHES_RESPONSE" | jq -r '.[0].name')

          if [ "$BRANCH_NAME" == "null" ] || [ -z "$BRANCH_NAME" ]; then
            echo "Warning: Could not find a branch where this commit is the HEAD."
            echo "This can happen if the tag points to an older commit."
            BRANCH_NAME="N/A"
          fi

          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Determine Environment
        id: environment
        run: |
          TAG="${{ steps.parsed_data.outputs.tag }}"
          ENV="production" # Default to production
          if [[ "$TAG" == *alpha* ]]; then
            ENV="development"
          elif [[ "$TAG" == *beta* ]]; then
            ENV="staging"
          fi
          echo "name=$ENV" >> $GITHUB_OUTPUT

      - name: Echo Extracted Information
        run: |
          echo "--- Extracted Information ---"
          echo "Commit SHA:   ${{ steps.parsed_data.outputs.sha }}"
          echo "Tag:          ${{ steps.parsed_data.outputs.tag }}"
          echo "Source Branch:${{ steps.branch_info.outputs.branch }}"
          echo "Environment:  ${{ steps.environment.outputs.name }}"
          echo "---------------------------"