name: Trigger on New Tag Push

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: read

jobs:
  call_orchestrator:
    name: Call Orchestrator Workflow
    uses: ./.github/workflows/orchestrator.yaml
    with:
      github_event: ${{ toJson(github.event) }}
      event_name: ${{ github.event_name}}