name: "Trigger on New Tag Push"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha\.[a-zA-Z0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta\.[a-zA-Z0-9]+'

permissions:
  contents: write
  pull-requests: read

jobs:
  call_orchestrator:
    name: Call Orchestrator Workflow
    uses: ./.github/workflows/orchestrator.yaml
    with:
      github_event: ${{ toJson(github.event) }}
      event_name: ${{ github.event_name }}