name: Trigger on New Tag

on:
  push:
    tags:
      - 'v*.*.*'
  issue_comment:
    types: [created]
    startsWith: '/service'

permissions: read-all

jobs:
  call_orchestrator:
    name: Call Orchestrator for Tag
    uses: ./.github/workflows/orchestrator.yaml
    with:
      github_event: ${{ toJson(github.event) }}
      event_name: ${{ github.event_name}}
