name: "Trigger on new tag push"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-(alpha|beta)'
      - 'v[0-9]+.[0-9]+.[0-9]+-(alpha|beta).[a-zA-Z0-9.-]+'

permissions:
  contents: write
  pull-requests: read

jobs:
  call_orchestrator:
    name: Call Orchestrator Workflow
    uses: ./.github/workflows/orchestrator.yaml
    with:
      # FIX: Ensure the event object is always passed as a valid JSON string
      github_event: ${{ toJson(github.event) }}
      event_name: ${{ github.event_name }}