apiVersion: v1
kind: Service
metadata:
  name: my-nginx-app-service
  namespace: my-nginx-app
spec:
  selector:
    app: my-nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
