apiVersion: v1
kind: Service
metadata:
  name: nginx-app-stg-service
  namespace: nginx-app-stg
spec:
  selector:
    app: nginx-app-stg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
